name: build
on: [push]

jobs:
  build:
    name: Build plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'
      - run: go build

